apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  replicas: 2
  # The selector field defines how the Deployment finds which Pods to manage
  selector: 
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: dockercloud/hello-world
          ports:
            - containerPort: 8080